### ISSUE TITLE
falsche ipv6  wiregurard-config 

### ISSUE THREAD

**Issue by poldy79** [freifunk-stuttgart/backbone#3]
Auf netinfo wird netinfag01n03a.conf anstelle von g01n03anetinfa.conf generiert. 
Konfiguration auf netinfo: 
PostUp = ip -6 address add local fd21:711:ffff:ffff::0:13:243/128 remote fd21:711:ffff:ffff::0:243:13/128 dev netinfag01n03a

Konfiguration auf gw01n03:
PostUp = ip -6 address add local fd21:711:ffff:ffff::0:13:243/128 remote fd21:711:ffff:ffff::0:243:13/128 dev g01n03anetinfa

das passt dann nicht zusammen. 

Wie soll das IP-Adressschema bei IPv6 sein? 
gw01n03 hat IP-offset 13
Soll die Lokale IP von gw01n03 fd21:711:ffff:ffff::0:13:243 oder fd21:711:ffff:ffff::0:243:13 sein?
Oder können wir wie bei IPv4 mit Point-to-Point auskommen, so dass bei der lokalen IPv6-Adresse der IP-Offset des Remoote keine Rolle mehr spielt?

**Comment by areyer** [comment]
behoben wie besprochen mit 9d2b5dae6382a180e5343ca67704c4714587800d und da7193bdd81a79c2af66e9cbbf7e304a4dd57962
