### ISSUE TITLE
syntax error in /etc/bird/bird_kernel.conf auf gw01n03

### ISSUE THREAD

**Issue by poldy79** [freifunk-stuttgart/backbone#4]
table tk_;
protocol kernel k_ from t_kernel {
        table tk_;  **#<-- hier fehtl was...** 
        kernel table ;
        export filter nodefaultroute;
}

**Comment by areyer** [comment]
Die Table IDs werden in /etc/ip_route2/rt_tables in Namen verwandelt, die dann hinter k_ bzw tk_ eingesetzt werden. Unbekannte Tabellen haben keinen Namen.
Quickfix: in /etc/iproute2/rt_tables  überflüssige Zeichen dort entfernen:
bin/create-config-mod-bird Zeile 79 macht das:
`cat /etc/iproute2/rt_tables |sed '/^#/d; /^25[345]/d; /^0/d' | while read rt_id rt_name; do`
D.h. Zeilen müssen entweder leer, mit # beginnend oder passend sein.
Alternativ: bessere excludes schreiben.
Hab die Zeile mit commit 825e205 verbessert.
