### ISSUE TITLE
/etc/bird/bird6_location_gw01n03.conf ohne linebreaks

### ISSUE THREAD

**Issue by poldy79** [freifunk-stuttgart/backbone#5]
Die Datei /etc/bird/bird6_location_gw01n03.conf wird ohne linebreaks generiert und ist somit schlecht lesbar (mit vim geöffnet)

**Comment by areyer** [comment]
Das ist Absicht, 1 Zeile pro Protokoll als Einzeiler. Gefällt mir so besser, ich hatte das früher anders, aber so siehst du mit einem breiten Monitor sofort worin sich die Zeilen unterscheiden.

**Comment by poldy79** [comment]
ok, dann mach ich die Schrift kleiner :-)
