### ISSUE TITLE
Line a und b vwenden gleiche IP-Konfiguration und ListenPort

### ISSUE THREAD

**Issue by poldy79** [freifunk-stuttgart/backbone#6]
Auf gw01n03 findet sich die folgende Config:
Betrifft v4 und v6. 

Zusätzlich ist in beiden Konfigurationen ListenPort = 12243 
führt zu RTNETLINK answers: Address already in use

Soweit mir bekannt, kann man nicht explizit auf v4 oder v6 binden. 

root@gw01n03:/var/lib/ffs/backbone/bin# diff  /etc/wireguard/g01n03anetinfa.conf /etc/wireguard/g01n03bnetinfb.conf 
6,7c6,7
< PostUp = ip address add local **100.100.0.13/32** remote **100.100.0.243/32** dev g01n03anetinfa
< PostUp = ip -6 address add local fd21:711:ffff:ffff::0:13/128 remote fd21:711:ffff:ffff::0:243/128 dev g01n03anetinfa
---
> PostUp = ip address add local **100.100.0.13/32** remote **100.100.0.243/32** dev g01n03bnetinfb
> PostUp = ip -6 address add local fd21:711:ffff:ffff::0:13/128 remote fd21:711:ffff:ffff::0:243/128 dev g01n03bnetinfb
12c12
< Endpoint = 89.163.142.247:12013
---
> Endpoint = 2001:4ba0:fff1:f8:68:b3:29:da:12013

**Comment by areyer** [comment]
fixed with 85d6584
